<img src="../logo/logo_ev2017.png">

# Table of Contents
* [1. El módulo NumPy](#1.-El-módulo-NumPy)
	* [1.1 Creación de arrays](#1.1-Creación-de-arrays)
	* [1.2 Operaciones](#1.2-Operaciones)
	* [1.3 Acceso y recorrido](#1.3-Acceso-y-recorrido)
		* [1.3.1 Arrays de una dimensión](#1.3.1-Arrays-de-una-dimensión)
		* [1.3.2 Arrays bidimensionales](#1.3.2-Arrays-bidimensionales)
	* [1.4 Uso de máscaras para selección de partes de un array](#1.4-Uso-de-máscaras-para-selección-de-partes-de-un-array)
	* [1.5 Métodos matemáticos y estadisticos](#1.5-Métodos-matemáticos-y-estadisticos)


#  El módulo NumPy

El módulo __NumPy__ (Numerical Python) es uno de los paquetes fundamentales en el contexto de la computación científica. Pproporciona funciones y rutinas matemáticas para la manipulación de __arrays y matrices de datos numéricos__ de una forma eficiente. 

__NumPy__ proporciona:

* El objeto __ndarray__: Un array multidimensional que permite realizar operaciones aritméticas sobre vectores muy eficientes. Es limilar a las listas pero añadiendo más eficiencia.
* Colección de funciones matemáticas muy eficientes que operan sobre  vectores (ndarrays) sin necesidad de escribir bucles (for o  while). Son más eficientes y rápidas que las operaciones sobre listas.
* Operaciones del álgebra lineal y genereación de números aleatorios.


El módulo __SciPy__ extiende la funcionalidad de __NumPy__ con una colección de algoritmos matemáticos (minimización, transformada de Fourier, regresión, ...).


In [1]:
# Para usar NumPy lo primero que debemos hacer es importarlo

import numpy as np        # lo importamos con un alias

##  Creación de arrays

Existen varias formas para crear un array.

* La forma más sencilla de crear un array es utilizando la función __array__ y una lista de objetos, que pueden ser otros arrays:

In [2]:
v = np.array( [1,2,3, 6, 0, 2] )
v

array([1, 2, 3, 6, 0, 2])

In [3]:
a = np.array( [[2,3,4], [5, 6, 7]] )
a

array([[2, 3, 4],
       [5, 6, 7]])

* Crear un array mediante la función __arange__. La función __arange__ crea un objeto de tipo __ndarray__.

In [4]:
# a diferencia de 'range', se pueden usar float 
a = np.arange( 0 , 5 , .5)     # números del 0 al 10(excluído) con paso 0.5
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


* Creación con datos aleatorios mediante la función __rand__ del módulo __Random__. La función __rand__ devuelve un número aleatorio procedente de una distribución uniforme en el intervalo [0,1).

In [5]:
# random es un submodulo dentro de numpy
a1 = np.random.rand(9)    # genera 10 números aleatorios dist.uniforme entre el 0 y el 1
a1

array([0.03197194, 0.61558693, 0.36087114, 0.9790233 , 0.29174897,
       0.56759106, 0.1007306 , 0.15332615, 0.45692661])

También podemos crear arrays de dos dimensiones:

In [6]:
# creacion de una matriz con distribucion uniforme [0,1)
a2 = np.random.rand(3, 4)     # valores aleatorios - 3 filas, 4 columnas
a2

array([[0.78024968, 0.17056902, 0.09926065, 0.49393248],
       [0.74297499, 0.97088671, 0.52847394, 0.84002026],
       [0.96367965, 0.42487595, 0.19561424, 0.13363052]])

##  Operaciones

Los operadores aritméticos aplicados a arrays, __se aplican elemento a elemento__.

Permite realizar operaciones sobre los arrays multidimensionales como si se tratara de operaciones sobre escales:

In [7]:
a = np.array( [[2,3,4], [5, 6, 7]] )
a

array([[2, 3, 4],
       [5, 6, 7]])

In [8]:
# multiplica cada elemento del array, python le hace broadcast al '10'
a * 10

array([[20, 30, 40],
       [50, 60, 70]])

__Operaciones aritméticas__

Operaciones suma, resta, multiplicación, etc...

Estas operaciones utilizan los operadores tradicionales, no se incluyen las operaciones matriciales las cuales
necesitan acceder por objetos

In [15]:
# para operar los arrays deben tener las mismas dimensiones o ser capaces de hacer broadcast (extender)
a = np.array([1,2,3], float) # el segundo argumento fuerza el tipado
b = np.array([5,2,6], float)

In [16]:
a + b

array([6., 4., 9.])

In [12]:
a - b 

array([-4.,  0., -3.])

>  Propiedades de los objetos __ndarray__:
> 
> - La propiedad `shape` que indica las dimensiones del array.
> - La propiedad `dtype` indica el tipo de los elementos almacenados en el array.

In [12]:
a.shape, a.dtype

((3,), dtype('float64'))

__Funciones universales__

Se trata de funciones que actúan sobre cada uno de los elementos de un array.

In [18]:
# funciones universales
array = np.array([-5, 60, -9])
b = np.abs(array) # algunas operaciones se realizan por modulo
b, b.max(), b.min() # otras operaciones se realizan por objeto

(array([ 5, 60,  9]), 60, 5)

In [14]:
b = np.square(array)
b

array([  25, 3600,   81], dtype=int32)

In [15]:
c = np.sqrt(b)  
c

array([ 5., 60.,  9.])

In [16]:
np.min(c)

5.0

In [17]:
np.maximum(a,b) # devuelve un array con el maximo en cada posicion entre ambos array argumento

array([  25., 3600.,   81.])

## Acceso y recorrido

### Arrays de una dimensión

Cuando trabajamos con arrays de una dimensión, el acceso a los elementos se realiza de forma similar a como se hace en el caso de listas o tuplas de elementos.

In [19]:
arr = np.arange(2, 20)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [20]:
len(arr)

18

In [21]:
arr[0]   

2

* Indexaciones iguales que en listas, podemos crear sub-arrays igual que con las sub-listas

Al jugar con sub-arrays asignandolos a otras variables, se utiliza referencia por lo tanto si se modifica la nueva variable, se modifica el array original del cual se obtuvo el sub-array

Para evitar que compartan memoria y sean dos arrays diferentes, se realiza una copia con ``c = a.copy()``

In [24]:
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2])

In [23]:
arr[1::3]

array([ 3,  6,  9, 12, 15, 18])

In [23]:
arr[-2:]

array([18, 19])

__Una diferencia importante con las listas__, es que las particiones de un ndarray mediante la notación [inicio:fin:paso] son vistas del array original. Todos los cambios realizados en las vistas, se reflejan en el array original:

In [26]:
# Las siguientes operaciones no las podriamos realizar de esta forma en listas
b = arr[-2:] # b es asignado a los dos ultimos elementos de arr
b[::] = 0 # asigna '0' a todos los elementos de b ya que indexa con [::] que es equivalente a todo el array
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,  0,
        0])

###  Arrays bidimensionales

El acceso a los elementos de un array bidimensional, se realiza indicando los índices separados por una coma.

In [28]:
b = np.array([[ 0,  1,  2,  3],
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [33]:
b[:,-1] # acceso a la ultima columna

array([ 3, 13, 23, 33, 43])

In [36]:
b[:2,:2] # acceso a la interseccion de las dos primeras columnas y las dos primeras filas

array([[ 0,  1],
       [10, 11]])

In [29]:
b[-2:, -2:] # acceso a la interseccion de las dos ultimas filas y dos ultimas columnas

array([[32, 33],
       [42, 43]])

In [27]:
b[1:3, : ]       # Acceso a los elementos de las filas 2 y 3 de todas las columnas

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

##  Uso de máscaras para selección de partes de un array

Otra forma de acceso a partes de un array de NumPy es mediante un array de booleanos que actúa como máscara. 

In [38]:
numbers = np.random.uniform(size=5)
numbers

array([0.27305225, 0.28842946, 0.53748164, 0.11682886, 0.51265446])

In [45]:
# operaciones booleanas sobre todos los elementos de un array
# devuelve un array de booleanos de la misma dimension que el original
( numbers > 0.5 ) & ( numbers < 0.8 )      # selecciona algunos elementos de b

array([False, False,  True, False,  True])

In [40]:
mascara = ( numbers > 0.5 ) & ( numbers < 0.8 )      
mascara

array([False, False,  True, False,  True])

In [41]:
numbers[mascara] # equivalente a numbers[(numbers>0.5)&(numbers<0.8)]

array([0.53748164, 0.51265446])

##  Métodos matemáticos y estadísticos

El módulo __NumPy__ proporciona métodos que permiten realizar otras operaciones, como el mínimo elemento de un array, el máximo, la media de los elementos de un array, etc.

  
> Se puede encontrar la lista de funciones en [scipy.org](http://wiki.scipy.org/Numpy_Example_List) 
>

In [46]:
mu = 0         # media
sigma = 0.1    # desviación
a = np.random.normal( mu, sigma, size = 10)    # distribución normal
a

array([ 0.00686349, -0.11803888, -0.00728337,  0.07881822, -0.11568678,
        0.1118714 ,  0.02050845, -0.11122295, -0.22182955,  0.02464506])

In [47]:
print( a.sum() )
print( a.min() , "--" , a.argmin() )
print( a.max() , "--" , a.argmax() ) 

-0.33135491857048754
-0.22182954508741198 -- 8
0.11187139861644756 -- 5


In [48]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [35]:
# suma de columnas para cada una de las filas con 'axis = 1'
print ( b.sum(axis = 1)  )   # suma por columnas

[  6  46  86 126 166]


__Media__

In [49]:
# media de todas las columnas
b.mean(axis = 0)

array([20., 21., 22., 23.])

In [37]:
np.mean(b)

21.5

__Varianza__

In [50]:
np.var(b, axis = 0)

array([200., 200., 200., 200.])

__Desviación estándard__

In [51]:
np.std(b, axis = 0)

array([14.14213562, 14.14213562, 14.14213562, 14.14213562])

__Mediana__

In [52]:
np.median(b)

21.5

__Correlación__


In [41]:
m = np.array([[10, 20, 30, 40],
              [12, 14, 16, 17]])

In [42]:
"""
Se calcula el coef. de correlación teniendo en cuenta que 
cada fila representa una variable
"""
np.corrcoef(m)      # correlación 

array([[1.        , 0.98977827],
       [0.98977827, 1.        ]])

##### Ejercicios

__* Dado el array `m1`, seleccionar los elementos de `m1` que son mayores que la media.__

In [53]:
m1 = np.random.rand(10)
m1

array([0.19326946, 0.04906028, 0.07098554, 0.99468385, 0.06018177,
       0.10066719, 0.08351388, 0.46201362, 0.09808365, 0.4383282 ])

In [59]:
# Solución
m1[(m1 > np.mean(m1))]

array([0.99468385, 0.46201362, 0.4383282 ])

* Dado el array `m2`, calcular la suma de todos los elementos de `m2`.


In [60]:
m2 = np.array([[10, 20, 30, 40],
              [12, 14, 16, 17]])


In [61]:
# Solución
m2.sum()

159

* Dado el array `m2`, calcular la suma de los elementos por columnas.


In [65]:
# Solución
m2.sum(axis = 0)

array([22, 34, 46, 57])

# References



* http://wiki.scipy.org/Tentative_NumPy_Tutorial
* http://wiki.scipy.org/SciPy
* [Python for Data Analysis](http://shop.oreilly.com/product/0636920023784.do)
