## Aplicación de NumPy

-----------------------

#### Ejemplo 1

Los datos contenidos en el fichero [datos.txt](./datos/datos.txt) describe las poblaciones de tres tipos de serpientes en el sur de Africa durante 20 años.

Cada columna comprende una especie y cada fila un año.

In [1]:
import numpy as np
data = np.loadtxt('./datos/datos.txt')    # carga de los datos
data

array([[ 2000., 30000.,  3000., 38300.],
       [ 2001., 37200.,  6100., 48200.],
       [ 2002., 60200.,  9800., 31600.],
       [ 2003., 77300., 36200., 38200.],
       [ 2004., 36300., 69300., 30600.],
       [ 2005., 20600., 31700., 49800.],
       [ 2006., 18100., 19000., 38600.],
       [ 2007., 21300., 13000., 32300.],
       [ 2008., 22000.,  8300., 43600.],
       [ 2009., 26300.,  9100., 32100.],
       [ 2010., 27100.,  7300., 36000.],
       [ 2011., 30300.,  8000., 36800.],
       [ 2012., 67000., 12300., 33800.],
       [ 2013., 76600., 19600., 30900.],
       [ 2014., 62300., 36700., 49300.],
       [ 2015., 19600., 61100., 39000.],
       [ 2016., 11200., 29700., 36700.],
       [ 2017.,  7600., 16800., 41800.],
       [ 2018., 13600.,  9700., 33300.],
       [ 2019., 16200., 10100., 31300.],
       [ 2020., 23700.,  8600., 47300.]])

* Cálculo de la media de población de cada tipo a lo largo del tiempo.


In [5]:
# Sol:
np.mean(data[:,1:], axis = 0) # elimino la primera columna de los anos

array([33547.61904762, 20257.14285714, 38071.42857143])

* Cálculo de la desviación estándar de la muestra

In [6]:
# Sol:
np.std(data[:,1:])

17958.196326990084

* ¿Qué especie ha tenido más población por año?

In [23]:
# Sol:
max_per_year = np.array([np.argmax(data[:,1:], axis =1), np.max(data[:,1:], axis = 1)]).T
max_per_year

array([[2.00e+00, 3.83e+04],
       [2.00e+00, 4.82e+04],
       [0.00e+00, 6.02e+04],
       [0.00e+00, 7.73e+04],
       [1.00e+00, 6.93e+04],
       [2.00e+00, 4.98e+04],
       [2.00e+00, 3.86e+04],
       [2.00e+00, 3.23e+04],
       [2.00e+00, 4.36e+04],
       [2.00e+00, 3.21e+04],
       [2.00e+00, 3.60e+04],
       [2.00e+00, 3.68e+04],
       [0.00e+00, 6.70e+04],
       [0.00e+00, 7.66e+04],
       [0.00e+00, 6.23e+04],
       [1.00e+00, 6.11e+04],
       [2.00e+00, 3.67e+04],
       [2.00e+00, 4.18e+04],
       [2.00e+00, 3.33e+04],
       [2.00e+00, 3.13e+04],
       [2.00e+00, 4.73e+04]])

In [25]:
max_year_specie = max_per_year[np.argmax(max_per_year[:,-1])]
print('La especie con mas poblacion por ano es la numero', max_year_specie[0], ' con poblacion', max_year_specie[1])

La especie con mas poblacion por ano es la numero 0.0  con poblacion 77300.0


In [29]:
print('El numero de veces que la especie 0 supera a los demas es', (max_per_year[:,0] == 0).sum())

El numero de veces que la especie 0 supera a los demas es 5
